//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gone_Sin_Mal_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gone_Sin_MalEntities : DbContext
    {
        public Gone_Sin_MalEntities()
            : base("name=Gone_Sin_MalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Favorite_Table> Favorite_Table { get; set; }
        public virtual DbSet<Notification_Table> Notification_Table { get; set; }
        public virtual DbSet<Package_Table> Package_Table { get; set; }
        public virtual DbSet<Promotion_Table> Promotion_Table { get; set; }
        public virtual DbSet<Restaurant_Table> Restaurant_Table { get; set; }
        public virtual DbSet<System_Table> System_Table { get; set; }
        public virtual DbSet<Transaction_Table> Transaction_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
        public virtual DbSet<Refund_Table> Refund_Table { get; set; }
    }
}
