//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gone_Sin_Mal_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Table
    {
        public long Package_id { get; set; }
        public string Package_type { get; set; }
        public Nullable<long> Package_coin_amount { get; set; }
        public string Myanpay_button_link { get; set; }
    }
}
