//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gone_Sin_Mal_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant_Table()
        {
            this.Promotion_Table = new HashSet<Promotion_Table>();
            this.User_Table = new HashSet<User_Table>();
        }
    
        public long Rest_id { get; set; }
        public string Rest_Name { get; set; }
        public string Rest_Password { get; set; }
        public byte[] Rest_Gallery_1 { get; set; }
        public byte[] Rest_Gallery_2 { get; set; }
        public byte[] Rest_Gallery_3 { get; set; }
        public byte[] Rest_Gallery_4 { get; set; }
        public Nullable<long> Rest_Coin { get; set; }
        public Nullable<long> Rest_special_coin { get; set; }
        public string Rest_email { get; set; }
        public string Rest_phno { get; set; }
        public string Rest_myanpay_name { get; set; }
        public string Rest_Township { get; set; }
        public string Rest_Location { get; set; }
        public string Rest_lat { get; set; }
        public string Rest_long { get; set; }
        public byte[] Rest_profile_picture { get; set; }
        public Nullable<long> User_id { get; set; }
        public Nullable<System.DateTime> Rest_created_date { get; set; }
        public Nullable<long> Rest_coin_purchased { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion_Table> Promotion_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Table> User_Table { get; set; }
        public virtual User_Table User_Table1 { get; set; }
    }
}
