//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gone_Sin_Mal_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Table
    {
        public long Record_id { get; set; }
        public string Masterkey { get; set; }
        public long Expired_coins { get; set; }
        public long Sold_coins { get; set; }
        public long Sold_special_coins { get; set; }
    }
}
