//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gone_Sin_Mal_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction_Table()
        {
            this.Notification_Table = new HashSet<Notification_Table>();
        }
    
        public long ID { get; set; }
        public long User_id { get; set; }
        public Nullable<long> Tran_id { get; set; }
        public string Tran_Type { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
    
        public virtual User_Table User_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification_Table> Notification_Table { get; set; }
    }
}
