//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gone_Sin_Mal_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Table()
        {
            this.Favorite_Table = new HashSet<Favorite_Table>();
            this.Notification_Table = new HashSet<Notification_Table>();
            this.Promotion_Table = new HashSet<Promotion_Table>();
            this.Restaurant_Table = new HashSet<Restaurant_Table>();
            this.Transaction_Table = new HashSet<Transaction_Table>();
        }
    
        public long User_id { get; set; }
        public string User_name { get; set; }
        public string User_noti_token { get; set; }
        public string User_type { get; set; }
        public string User_township { get; set; }
        public Nullable<long> User_available_coin { get; set; }
        public Nullable<long> User_visited_restaurant { get; set; }
        public Nullable<System.DateTime> User_exceeded_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_Table> Favorite_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification_Table> Notification_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion_Table> Promotion_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant_Table> Restaurant_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Table> Transaction_Table { get; set; }
    }
}
